"""Add user auth fields

Revision ID: f4b3c7487bdf
Revises: 386e8fe32568
Create Date: 2026-06-17 13:40:52.502023

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4b3c7487bdf"
down_revision: Union[str, Sequence[str], None] = "386e8fe32568"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "hashed_password", sa.String(length=255), server_default="", nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
